future: true
permalink: /:title/
url: http://blog.zs.center
name: Blog学习
author: ihaiu
qq: 593705098
email: ihaiu@qq.com
cnzz: 1260003113
weibo: zengfeng75
github: ihaiucom
paginate: 20
truncate: true
about: "爱海游"